### ISSUE TITLE
Very complex frontend routing configuration

### ISSUE THREAD

**Issue by JumpLink** [beabee-communityrm/monorepo#1]
After much trial and error, I think I now know why I failed to test the docker image of the frontend locally. 

It took me a long time to understand how the frontend docker image works. Here is a summary:

# When the frontend is started locally without docker:

* A local development server is started using `vite`
* Within this development server, a proxy is started which forwards all requests corresponding to the regular expression `^/(api|login|upload|uploads|favicon.png)` to the URL `API_PROXY_URL` (which is `http://localhost:3001` by default), this is the router of the backend docker compose stack which is accessible from outside via the IP `3001`:

vite.config.js:

    ```js
    server: {
      port: 3000,
      // Proxy API requests to the backend
      proxy: {
        ‘^/(api|login|upload|uploads|favicon.png)’: {
          target: env.API_PROXY_URL,
          changeOrigin: true,
          cookieDomainRewrite: ‘localhost’,
        },
      },
    },
    ```

docker-compose.yml:

```yml
  router:
    build:
      context: ../..
      dockerfile: ./apps/backend/Dockerfile
      target: router
    volumes:
      - ./built/static:/opt/built/static:ro
    ports:
      - ${MAIN_PORT}:80
 ```

`MAIN_PORT` is `3001` by default

* The Docker Nginx WebServer of the backend forwards the requests forwarded by vite in turn to the corresponding services, for example requests matching the regular expression `^/api/(.*)$` are forwarded to the backend:

    ```conf
    location ~ ^/api/(.*)$ {
        proxy_pass $api_app/$1$is_args$args;
    }
    ```
